sudo: false
language: go
env:
    global:
        - PATH="$HOME/gopath/bin:$HOME/bin:$PATH"
notifications:
    email:
        on_success: never

go:
    - 1.5.3
    - 1.6
    - tip

script:
    - make test
