sudo: false
language: go
os:
    - linux
    - osx
env:
    global:
        - PATH="$HOME/gopath/bin:$HOME/bin:$PATH"

# need to fix the linter before enabling tip again
# matrix:
#     include:
#         - os: linux
#           go: tip

notifications:
    email:
        on_success: never

go:
    - 1.6.4
    - 1.7.4

script:
    - make test
