sudo: false
language: go
env:
    global:
        - PATH="$HOME/gopath/bin:$HOME/bin:$PATH"

go:
    - 1.4.3
    - 1.5.3
    - tip

before_install:
    - go get golang.org/x/tools/cmd/vet
    - go get github.com/golang/lint/golint

script:
    - go vet -x ./...
    - golint ./...
    - go test -v -cover ./...
