sudo: false
language: go
os:
    - linux
    - osx
env:
    global:
        - PATH="$HOME/gopath/bin:$HOME/bin:$PATH"

# need to fix the linter before enabling tip again
matrix:
    include:
        - os: linux
          go: tip

notifications:
    email:
        on_success: never

go:
    - 1.7.6
    - 1.8.3

before_install:
    - go get github.com/mattn/goveralls

script:
    - make test
    - goveralls -service=travis-ci
