sudo: false
language: go
os:
    - linux
    - osx
env:
    global:
        - PATH="$HOME/gopath/bin:$HOME/bin:$PATH"

matrix:
    include:
        - os: linux
          go: tip

notifications:
    email:
        on_success: never

go:
    - 1.5.4
    - 1.6.2

script:
    - make test
